<?php

namespace app\admin\controller;

use app\common\model\User as UserModel;
use think\Request;

class User extends AdminBase
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->assign('search_types', UserModel::TYPE_OF_SEARCH);
    }

    public function index(Request $request)
    {
        $users = UserModel::paginate(15, false, $request->param());
        return view('index', compact('users'));
    }

    /* 用户检索 */
    public function search(Request $request)
    {
        $searchKey = $request->post('searchKey', '');
        $searchType = $request->post('searchType', UserModel::SEARCH_NICKNAME);
        switch ($searchType) {
            case UserModel::SEARCH_NICKNAME:
                $where['name'] = ['like', '%' . $searchKey . '%'];
                break;
            case UserModel::SEARCH_UUID:
                $where['id'] = $searchKey;
                break;
            case UserModel::SEARCH_PHONE:
                $where['phone'] = $searchKey;
                break;
            case UserModel::SEARCH_MEMBER:
                $where['is_member'] = UserModel::VIP;
                break;
            case UserModel::SEARCH_NOT_MEMBER:
                $where['is_member'] = UserModel::NORMAL;
                break;
            case UserModel::SEARCH_ALL:
                $where = [];
                break;
        }
        $users = UserModel::where($where)->paginate(15, false, $request->param())
            ->appends(['searchKey' => $searchKey, 'searchType' => $searchType]);
        return view('index', compact('users', 'searchKey', 'searchType'));
    }
}